/* Story Quest — Science Lab Data
   30 elements (3 tiers × 10), 12 compounds, mix lab recipes, states of matter, quizzes */

// ======== ELEMENTS (3 tiers) ========
const ELEMENTS = {
  beginner: [
    { symbol: "H", name: "Hydrogen", emoji: "💨", number: 1, state: "gas", category: "Non-metal",
      description: "The lightest gas in the universe!",
      findIt: ["🌟 Stars", "💧 Water", "☀️ The Sun"],
      origin: "From Greek 'hydro' (water) + 'genes' (maker) — it makes water! Think: H = Hydro",
      pronunciation: "HY-druh-jun", funFact: "Hydrogen makes up about 75% of all the stuff in the universe!" },
    { symbol: "He", name: "Helium", emoji: "🎈", number: 2, state: "gas", category: "Noble Gas",
      description: "The gas that makes balloons float!",
      findIt: ["🎈 Balloons", "☀️ The Sun", "🌟 Stars"],
      origin: "Named after 'Helios', the Greek god of the Sun — it was first found in sunlight! Think: He = Helios",
      pronunciation: "HEE-lee-um", funFact: "Helium makes your voice squeaky because sound travels faster through it!" },
    { symbol: "C", name: "Carbon", emoji: "✏️", number: 6, state: "solid", category: "Non-metal",
      description: "Found in everything alive — and in pencils!",
      findIt: ["✏️ Pencil lead", "💎 Diamonds", "🌲 Trees"],
      origin: "From Latin 'carbo' meaning 'coal' — because charcoal is mostly carbon! Think: C = Coal",
      pronunciation: "KAR-bun", funFact: "Diamonds and pencil lead are both made of carbon, just arranged differently!" },
    { symbol: "N", name: "Nitrogen", emoji: "🌬️", number: 7, state: "gas", category: "Non-metal",
      description: "Most of the air you breathe is nitrogen!",
      findIt: ["🌬️ Air (78%)", "🌱 Plant food", "❄️ Liquid nitrogen"],
      origin: "From Greek 'nitron' + 'genes' — it was found in a mineral called niter. Think: N = Nitro",
      pronunciation: "NY-truh-jun", funFact: "About 78% of the air around you right now is nitrogen!" },
    { symbol: "O", name: "Oxygen", emoji: "🫁", number: 8, state: "gas", category: "Non-metal",
      description: "The gas you need to breathe and stay alive!",
      findIt: ["🫁 Your lungs", "💧 Water", "🔥 Fire needs it"],
      origin: "From Greek 'oxy' (sharp/acid) + 'genes' (maker) — they thought it made acids. Think: O = Oxy",
      pronunciation: "OX-ih-jun", funFact: "Your body is about 65% oxygen by weight — mostly in water!" },
    { symbol: "Fe", name: "Iron", emoji: "🧲", number: 26, state: "solid", category: "Metal",
      description: "A super strong metal used in buildings and magnets!",
      findIt: ["🧲 Magnets", "🩸 Your blood", "🌉 Bridges"],
      origin: "Symbol from Latin 'Ferrum' meaning iron. Think: Fe = Ferrum",
      pronunciation: "EYE-urn", funFact: "Your blood is red because it contains iron — the same metal in nails!" },
    { symbol: "Au", name: "Gold", emoji: "🥇", number: 79, state: "solid", category: "Metal",
      description: "A shiny yellow metal that never rusts!",
      findIt: ["💍 Jewelry", "🏆 Trophies", "📱 Inside phones"],
      origin: "Symbol from Latin 'Aurum' meaning 'shining dawn'. Think: Au = Aurum (shiny!)",
      pronunciation: "gohld", funFact: "All the gold ever mined would fit in about 3 Olympic swimming pools!" },
    { symbol: "Ag", name: "Silver", emoji: "🪙", number: 47, state: "solid", category: "Metal",
      description: "A shiny metal that conducts electricity the best!",
      findIt: ["🪙 Coins", "🪞 Mirrors", "📸 Old cameras"],
      origin: "Symbol from Latin 'Argentum' meaning silver. Argentina is named after it! Think: Ag = Argentum",
      pronunciation: "SIL-vur", funFact: "Silver is the best conductor of electricity of any element!" },
    { symbol: "Cu", name: "Copper", emoji: "🪙", number: 29, state: "solid", category: "Metal",
      description: "An orange-brown metal used in wires and pennies!",
      findIt: ["🔌 Electric wires", "🪙 Pennies", "🗽 Statue of Liberty"],
      origin: "Symbol from Latin 'Cuprum', from the island of Cyprus where it was mined. Think: Cu = Cuprum",
      pronunciation: "KAH-pur", funFact: "The Statue of Liberty is made of copper — it turned green over time!" },
    { symbol: "Ca", name: "Calcium", emoji: "🦴", number: 20, state: "solid", category: "Metal",
      description: "Makes your bones and teeth strong!",
      findIt: ["🦴 Bones", "🦷 Teeth", "🥛 Milk"],
      origin: "From Latin 'calx' meaning 'lime' — limestone is full of calcium. Think: Ca = Calcium in chalk",
      pronunciation: "KAL-see-um", funFact: "Your body has about 2 pounds of calcium, mostly in your bones and teeth!" }
  ],
  intermediate: [
    { symbol: "Na", name: "Sodium", emoji: "🧂", number: 11, state: "solid", category: "Metal",
      description: "Half of table salt — and it explodes in water!",
      findIt: ["🧂 Salt", "🥤 Baking soda", "💡 Street lights (yellow)"],
      origin: "Symbol from Latin 'Natrium'. Sodium itself comes from 'soda'. Think: Na = Natrium",
      pronunciation: "SOH-dee-um", funFact: "Sodium is so soft you can cut it with a butter knife, but it explodes when it touches water!" },
    { symbol: "Cl", name: "Chlorine", emoji: "🏊", number: 17, state: "gas", category: "Non-metal",
      description: "The other half of salt — keeps pools clean!",
      findIt: ["🏊 Swimming pools", "🧂 Salt", "🚰 Clean water"],
      origin: "From Greek 'chloros' meaning 'pale green' — it's a greenish gas. Think: Cl = Chloros (green)",
      pronunciation: "KLOR-een", funFact: "Chlorine is a stinky green gas by itself, but with sodium it makes the salt on your fries!" },
    { symbol: "S", name: "Sulfur", emoji: "🌋", number: 16, state: "solid", category: "Non-metal",
      description: "A yellow element that smells like rotten eggs!",
      findIt: ["🌋 Volcanoes", "🧄 Garlic smell", "🔥 Matches"],
      origin: "From Latin 'sulphur' — ancient people called it 'brimstone'. Think: S = Stinky!",
      pronunciation: "SUL-fur", funFact: "The stinky smell of rotten eggs comes from hydrogen sulfide gas!" },
    { symbol: "K", name: "Potassium", emoji: "🍌", number: 19, state: "solid", category: "Metal",
      description: "Found in bananas — helps your muscles work!",
      findIt: ["🍌 Bananas", "🥔 Potatoes", "💪 Muscles"],
      origin: "Symbol from Latin 'Kalium' meaning 'potash' (ashes from burning plants). Think: K = Kalium",
      pronunciation: "puh-TAS-ee-um", funFact: "Bananas are famous for potassium, but potatoes actually have more!" },
    { symbol: "Al", name: "Aluminum", emoji: "🥫", number: 13, state: "solid", category: "Metal",
      description: "A lightweight metal used in cans and foil!",
      findIt: ["🥫 Soda cans", "✈️ Airplanes", "🫕 Foil"],
      origin: "From Latin 'alumen' meaning a bitter salt used for dyeing. Think: Al = Aluminum foil",
      pronunciation: "uh-LOO-mih-num", funFact: "Aluminum used to be more expensive than gold until scientists found an easy way to make it!" },
    { symbol: "Si", name: "Silicon", emoji: "💻", number: 14, state: "solid", category: "Non-metal",
      description: "Used in computer chips — Silicon Valley is named after it!",
      findIt: ["💻 Computer chips", "🏖️ Sand", "🪟 Glass"],
      origin: "From Latin 'silex' meaning 'flint' (a type of rock). Think: Si = Silicon Valley",
      pronunciation: "SIL-ih-kon", funFact: "Sand on the beach is mostly silicon dioxide — the same stuff used to make glass and computer chips!" },
    { symbol: "Pb", name: "Lead", emoji: "⚓", number: 82, state: "solid", category: "Metal",
      description: "A very heavy metal — don't eat it, it's poisonous!",
      findIt: ["🔋 Old batteries", "⚓ Fishing weights", "🛡️ X-ray shields"],
      origin: "Symbol from Latin 'Plumbum' — plumbers originally worked with lead pipes! Think: Pb = Plumbum",
      pronunciation: "led", funFact: "Lead is so dense it can block X-rays, which is why you wear a lead apron at the dentist!" },
    { symbol: "Sn", name: "Tin", emoji: "🥫", number: 50, state: "solid", category: "Metal",
      description: "A soft metal used to coat cans so they don't rust!",
      findIt: ["🥫 Tin cans", "🫕 Tin foil", "🔔 Tin whistles"],
      origin: "Symbol from Latin 'Stannum'. Think: Sn = Stannum (sounds fancy!)",
      pronunciation: "tin", funFact: "When tin gets very cold, it can crumble to powder — called 'tin pest'!" },
    { symbol: "Zn", name: "Zinc", emoji: "🛡️", number: 30, state: "solid", category: "Metal",
      description: "Protects other metals from rusting — like a shield!",
      findIt: ["🔩 Nails coating", "☀️ Sunscreen", "🩹 Healing cream"],
      origin: "From German 'Zinke' meaning 'pointed' because zinc crystals look spiky. Think: Zn = Zinc spikes",
      pronunciation: "zink", funFact: "Zinc is in sunscreen — that white stuff on lifeguards' noses is zinc oxide!" },
    { symbol: "P", name: "Phosphorus", emoji: "✨", number: 15, state: "solid", category: "Non-metal",
      description: "Glows in the dark and is in your DNA!",
      findIt: ["🧬 Your DNA", "🔥 Match tips", "✨ Glow sticks"],
      origin: "From Greek 'phosphoros' meaning 'light-bearer' — it glows! Think: P = Phosphorus glows",
      pronunciation: "FOS-fur-us", funFact: "White phosphorus glows in the dark and can catch fire by itself in air!" }
  ],
  advanced: [
    { symbol: "Pt", name: "Platinum", emoji: "💎", number: 78, state: "solid", category: "Metal",
      description: "Rarer than gold — used in jewelry and car exhaust cleaners!",
      findIt: ["💍 Fancy jewelry", "🚗 Car catalytic converters", "💳 Credit cards (Platinum!)"],
      origin: "From Spanish 'platina' meaning 'little silver'. Think: Pt = Platina",
      pronunciation: "PLAT-ih-num", funFact: "Platinum is so rare that all the platinum ever mined would fit in your living room!" },
    { symbol: "Ti", name: "Titanium", emoji: "🦿", number: 22, state: "solid", category: "Metal",
      description: "Super strong but super light — used in spacecraft!",
      findIt: ["🚀 Rockets", "🦿 Artificial joints", "✈️ Jet engines"],
      origin: "Named after the Titans — powerful giants from Greek mythology! Think: Ti = Titans",
      pronunciation: "ty-TAY-nee-um", funFact: "Titanium is as strong as steel but almost half the weight!" },
    { symbol: "Ni", name: "Nickel", emoji: "🪙", number: 28, state: "solid", category: "Metal",
      description: "A shiny metal used in coins and stainless steel!",
      findIt: ["🪙 5-cent coin", "🍴 Stainless steel", "🔋 Batteries"],
      origin: "From German 'Kupfernickel' meaning 'goblin copper' — miners thought goblins cursed it! Think: Ni = Nickel coin",
      pronunciation: "NIK-ul", funFact: "The US nickel coin is actually 75% copper and only 25% nickel!" },
    { symbol: "Co", name: "Cobalt", emoji: "🔵", number: 27, state: "solid", category: "Metal",
      description: "Makes beautiful blue colors and rechargeable batteries!",
      findIt: ["🎨 Blue paint", "🔋 Phone batteries", "🏺 Blue pottery"],
      origin: "From German 'Kobald' meaning 'goblin' — miners blamed goblins for cobalt's tricky ores. Think: Co = Cobalt blue",
      pronunciation: "KOH-bolt", funFact: "Cobalt has been used to make blue glass and pottery for over 4,000 years!" },
    { symbol: "Mn", name: "Manganese", emoji: "🔋", number: 25, state: "solid", category: "Metal",
      description: "Helps make steel stronger and batteries work!",
      findIt: ["🔋 Batteries", "🚂 Railroad tracks", "🥤 Soda cans"],
      origin: "From Latin 'magnes' meaning 'magnet' — it was confused with magnetite. Think: Mn = Magnet-ese",
      pronunciation: "MANG-guh-neez", funFact: "About 90% of all manganese produced goes into making steel stronger!" },
    { symbol: "Cr", name: "Chromium", emoji: "🪞", number: 24, state: "solid", category: "Metal",
      description: "Makes things shiny and colorful — chrome bumpers!",
      findIt: ["🚗 Chrome bumpers", "💎 Rubies (red!)", "💚 Emeralds (green!)"],
      origin: "From Greek 'chroma' meaning 'color' — it makes many colorful compounds! Think: Cr = Chroma (color)",
      pronunciation: "KROH-mee-um", funFact: "Chromium makes rubies red AND emeralds green — the same element, different colors!" },
    { symbol: "W", name: "Tungsten", emoji: "💡", number: 74, state: "solid", category: "Metal",
      description: "Has the highest melting point of any metal!",
      findIt: ["💡 Old light bulbs", "🎯 Darts", "⚙️ Drill bits"],
      origin: "Symbol W from German 'Wolfram'. Tungsten means 'heavy stone' in Swedish. Think: W = Wolfram",
      pronunciation: "TUNG-stun", funFact: "Tungsten melts at 6,192°F — hot enough to survive inside a rocket engine!" },
    { symbol: "U", name: "Uranium", emoji: "☢️", number: 92, state: "solid", category: "Metal",
      description: "A radioactive metal used for nuclear energy!",
      findIt: ["⚡ Nuclear power plants", "🔬 Science labs", "🌍 Deep underground"],
      origin: "Named after the planet Uranus, which was discovered 8 years before uranium. Think: U = Uranus",
      pronunciation: "yoo-RAY-nee-um", funFact: "A piece of uranium the size of a golf ball has as much energy as 20 tons of coal!" },
    { symbol: "Ne", name: "Neon", emoji: "💡", number: 10, state: "gas", category: "Noble Gas",
      description: "Makes bright glowing signs — especially red-orange!",
      findIt: ["🔴 Neon signs", "📺 TV screens", "⚡ Lightning"],
      origin: "From Greek 'neos' meaning 'new' — it was a newly discovered gas! Think: Ne = New (neos)",
      pronunciation: "NEE-on", funFact: "True neon signs glow red-orange. Other 'neon' colors actually use different gases!" },
    { symbol: "Ar", name: "Argon", emoji: "💡", number: 18, state: "gas", category: "Noble Gas",
      description: "A lazy gas that doesn't react with anything!",
      findIt: ["💡 Light bulbs (inside!)", "🌬️ Air (1%)", "⚡ Welding"],
      origin: "From Greek 'argos' meaning 'lazy' or 'inactive' — because it doesn't react! Think: Ar = Argos (lazy)",
      pronunciation: "AR-gon", funFact: "About 1% of the air you breathe is argon — the third most common gas in our atmosphere!" }
  ]
};

// ======== STATES OF MATTER ========
const STATES_OF_MATTER = [
  {
    state: "solid", emoji: "🧊", color: "#6C8EBF",
    title: "Solids",
    description: "Particles are packed tightly together and vibrate in place. Solids keep their shape!",
    examples: ["🧊 Ice", "🪨 Rocks", "🪵 Wood", "💎 Diamonds", "🦴 Bones"],
    funFact: "Even though solids seem still, their tiny particles are always vibrating!"
  },
  {
    state: "liquid", emoji: "💧", color: "#5BA4CF",
    title: "Liquids",
    description: "Particles are close together but can slide past each other. Liquids take the shape of their container!",
    examples: ["💧 Water", "🥛 Milk", "🍯 Honey", "🧴 Shampoo", "🩸 Blood"],
    funFact: "Mercury is the only metal that's a liquid at room temperature!"
  },
  {
    state: "gas", emoji: "💨", color: "#A8D8A8",
    title: "Gases",
    description: "Particles are spread far apart and zoom around freely. Gases fill up any space!",
    examples: ["💨 Air", "🎈 Helium", "💨 Steam", "🌬️ Wind", "😮‍💨 Your breath"],
    funFact: "Air is actually a mixture of gases — mostly nitrogen (78%) and oxygen (21%)!"
  }
];

const STATE_CHANGES = [
  { from: "solid", to: "liquid", name: "Melting", emoji: "🧊➡️💧", example: "Ice cream melting on a hot day" },
  { from: "liquid", to: "gas", name: "Evaporation", emoji: "💧➡️💨", example: "Puddles disappearing after rain" },
  { from: "gas", to: "liquid", name: "Condensation", emoji: "💨➡️💧", example: "Water drops on a cold glass" },
  { from: "liquid", to: "solid", name: "Freezing", emoji: "💧➡️🧊", example: "Water turning into ice cubes" },
  { from: "solid", to: "gas", name: "Sublimation", emoji: "🧊➡️💨", example: "Dry ice turning directly into fog" },
  { from: "gas", to: "solid", name: "Deposition", emoji: "💨➡️🧊", example: "Frost forming on a cold window" }
];

// ======== COMPOUNDS (for Equation Builder) ========
const COMPOUNDS = [
  { name: "Water", formula: "H₂O", elements: ["H","H","O"], emoji: "💧", difficulty: "beginner",
    hint: "You drink this every day!",
    explanation: "Water is in every raindrop, river, and ocean. Your body is about 60% water! It can be liquid (water), solid (ice), or gas (steam). Two tiny hydrogen atoms bond with one oxygen atom to create the most important liquid on Earth." },
  { name: "Carbon Dioxide", formula: "CO₂", elements: ["C","O","O"], emoji: "🫧", difficulty: "beginner",
    hint: "The bubbles in soda!",
    explanation: "You breathe this out every time you exhale! Plants breathe it IN to make food through photosynthesis. It makes the fizzy bubbles in soda and sparkling water. Too much CO₂ in the atmosphere causes global warming." },
  { name: "Table Salt", formula: "NaCl", elements: ["Na","Cl"], emoji: "🧂", difficulty: "beginner",
    hint: "You put this on food to make it taste better!",
    explanation: "Sodium is a metal that explodes in water. Chlorine is a stinky poisonous gas. But together they make the yummy salt on your french fries! The ocean is salty because rivers wash salt from rocks into the sea." },
  { name: "Rust", formula: "Fe₂O₃", elements: ["Fe","Fe","O","O","O"], emoji: "🟤", difficulty: "intermediate",
    hint: "This makes metal turn orange-brown when it gets wet!",
    explanation: "When iron meets water and oxygen, it slowly turns into rust. That's why we paint metal — to keep water away! Mars is called the Red Planet because its surface is covered in iron rust. Even your old bike can get rusty if left in the rain!" },
  { name: "Baking Soda", formula: "NaHCO₃", elements: ["Na","H","C","O","O","O"], emoji: "🧁", difficulty: "intermediate",
    hint: "Makes cakes and cookies rise in the oven!",
    explanation: "When baking soda meets something acidic (like vinegar), it creates CO₂ bubbles that make things fizz and rise. That's how cakes get fluffy! You can also use it to clean things, get rid of bad smells, and even make a volcano science project!" },
  { name: "Laughing Gas", formula: "N₂O", elements: ["N","N","O"], emoji: "😂", difficulty: "intermediate",
    hint: "Dentists sometimes use this to help you relax!",
    explanation: "Nitrous oxide is called 'laughing gas' because when you breathe a little of it, it makes you feel giggly and happy. Dentists use it so patients don't feel nervous. It was discovered in 1772 and people used to have 'laughing gas parties'!" },
  { name: "Ammonia", formula: "NH₃", elements: ["N","H","H","H"], emoji: "🧹", difficulty: "intermediate",
    hint: "A strong-smelling cleaning liquid!",
    explanation: "Ammonia has a super strong smell — you'd recognize it right away! It's used in window cleaners and floor cleaners. It's also used to make fertilizer that helps plants grow. Some animals, like cats, can smell ammonia much better than humans." },
  { name: "Limestone", formula: "CaCO₃", elements: ["Ca","C","O","O","O"], emoji: "🏛️", difficulty: "advanced",
    hint: "Ancient buildings like the pyramids are made from this!",
    explanation: "Limestone is made of calcium, carbon, and oxygen. The Egyptian pyramids, the White Cliffs of Dover, and many old churches are built from limestone. Seashells and coral are also made of calcium carbonate! When you pour vinegar on limestone, it fizzes." },
  { name: "Methane", formula: "CH₄", elements: ["C","H","H","H","H"], emoji: "🔥", difficulty: "advanced",
    hint: "The gas in natural gas stoves!",
    explanation: "Methane is the main ingredient in natural gas — the gas many homes use for cooking and heating. Cows burp a LOT of methane (seriously!), which affects climate change. It's also found on other planets like Jupiter and Saturn." },
  { name: "Hydrogen Peroxide", formula: "H₂O₂", elements: ["H","H","O","O"], emoji: "🫧", difficulty: "advanced",
    hint: "Looks like water but fizzes on cuts!",
    explanation: "Hydrogen peroxide looks just like water but has one extra oxygen atom. When you put it on a cut, the fizzing you see is oxygen being released — your body's enzymes break it apart! Some people use it to lighten their hair blonde. It's also used in rocket fuel!" },
  { name: "Sugar", formula: "C₆H₁₂O₆", elements: ["C","C","C","C","C","C","H","H","H","H","H","H","H","H","H","H","H","H","O","O","O","O","O","O"], emoji: "🍬", difficulty: "advanced",
    hint: "Makes candy and cookies taste sweet!",
    explanation: "One tiny crystal of sugar has 24 atoms packed inside! Sugar comes from sugarcane or sugar beets. Your body breaks down sugar to get energy for running, thinking, and playing. That's why you feel energetic after eating something sweet!" },
  { name: "Copper Sulfate", formula: "CuSO₄", elements: ["Cu","S","O","O","O","O"], emoji: "💙", difficulty: "advanced",
    hint: "Makes beautiful bright blue crystals!",
    explanation: "Copper sulfate makes stunning bright blue crystals that look like gems! Scientists use it in experiments, farmers use it to protect plants from fungus, and artists have used its blue color in paintings for hundreds of years. You can even grow your own crystals with it!" }
];

// ======== MIX LAB RECIPES ========
const MIX_INGREDIENTS = [
  { id: "vinegar", name: "Vinegar", emoji: "🍶", color: "#F5E6CC" },
  { id: "baking-soda", name: "Baking Soda", emoji: "🧂", color: "#FFFFFF" },
  { id: "water", name: "Water", emoji: "💧", color: "#B3E0FF" },
  { id: "oil", name: "Oil", emoji: "🫒", color: "#FFD700" },
  { id: "food-coloring", name: "Food Coloring", emoji: "🎨", color: "#FF6B81" },
  { id: "lemon-juice", name: "Lemon Juice", emoji: "🍋", color: "#FFF9C4" },
  { id: "milk", name: "Milk", emoji: "🥛", color: "#FAFAFA" },
  { id: "cornstarch", name: "Cornstarch", emoji: "🌽", color: "#FFF8E1" },
  { id: "salt", name: "Salt", emoji: "🧂", color: "#F5F5F5" },
  { id: "ice", name: "Ice", emoji: "🧊", color: "#E3F2FD" },
  { id: "dish-soap", name: "Dish Soap", emoji: "🧴", color: "#A5D6A7" },
  { id: "pepper", name: "Pepper", emoji: "🫑", color: "#5D4037" }
];

const MIX_RECIPES = [
  { name: "Volcano Eruption", ingredients: ["vinegar", "baking-soda"], emoji: "🌋",
    reaction: "FIZZZZ! The baking soda and vinegar react to make carbon dioxide gas — that's the bubbles erupting like a volcano!",
    science: "This is an acid-base reaction. Vinegar (acid) + baking soda (base) = carbon dioxide gas + water + sodium acetate." },
  { name: "Lava Lamp", ingredients: ["water", "oil", "food-coloring"], emoji: "🫧",
    reaction: "The colored water sinks through the oil and creates beautiful blobs — just like a lava lamp!",
    science: "Oil and water don't mix because water molecules stick together (they're polar) and oil molecules are non-polar. The food coloring only dissolves in water!" },
  { name: "Magic Oobleck", ingredients: ["cornstarch", "water"], emoji: "🪄",
    reaction: "It's a liquid... no wait, it's a solid! Squeeze it and it's hard. Let go and it flows!",
    science: "This is a non-Newtonian fluid — it acts like a solid when you push on it fast, but flows like a liquid when you're gentle." },
  { name: "Fizzy Lemonade", ingredients: ["lemon-juice", "baking-soda"], emoji: "🍋",
    reaction: "Bubble bubble! The lemon juice and baking soda fizz and foam like a science experiment you can drink!",
    science: "Lemon juice is an acid (citric acid) that reacts with baking soda (a base) to produce CO₂ bubbles — natural carbonation!" },
  { name: "Magic Milk", ingredients: ["milk", "food-coloring", "dish-soap"], emoji: "🌈",
    reaction: "The colors EXPLODE outward and swirl in beautiful patterns!",
    science: "Dish soap breaks apart the fat molecules in milk. As the fat moves away from the soap, it pushes the food coloring around!" },
  { name: "Pepper Scatter", ingredients: ["water", "pepper", "dish-soap"], emoji: "✨",
    reaction: "Touch the soap to the water and — ZOOM! The pepper races away like magic!",
    science: "Water has surface tension that holds the pepper up. Soap breaks the surface tension, so the water pulls away from the soap, dragging the pepper with it!" },
  { name: "Ice Cream in a Bag", ingredients: ["milk", "ice", "salt"], emoji: "🍦",
    reaction: "The milk gets colder and colder until it thickens into creamy ice cream!",
    science: "Salt lowers the freezing point of ice, making it super cold (below 0°C). This extreme cold freezes the milk into ice cream!" },
  { name: "Elephant Toothpaste", ingredients: ["water", "dish-soap", "food-coloring"], emoji: "🐘",
    reaction: "A giant foam snake erupts from the container — it looks like toothpaste for an elephant!",
    science: "In the real experiment, hydrogen peroxide breaks down rapidly with yeast, releasing oxygen gas. The soap traps the oxygen into tons of foam!" }
];

// ======== QUIZ QUESTIONS (for Element Explorer & State Sorter) ========
const ELEMENT_QUIZ = {
  beginner: [
    { q: "What is the lightest element?", options: ["Oxygen", "Hydrogen", "Helium", "Carbon"], correct: 1 },
    { q: "Which element makes balloons float?", options: ["Hydrogen", "Nitrogen", "Helium", "Oxygen"], correct: 2 },
    { q: "What element is in pencil lead?", options: ["Iron", "Lead", "Carbon", "Gold"], correct: 2 },
    { q: "What do you breathe to stay alive?", options: ["Nitrogen", "Carbon", "Helium", "Oxygen"], correct: 3 },
    { q: "What metal makes your blood red?", options: ["Copper", "Gold", "Iron", "Silver"], correct: 2 },
    { q: "What symbol does Gold have?", options: ["Go", "Gd", "Au", "Ag"], correct: 2 },
    { q: "What element is in your bones?", options: ["Iron", "Calcium", "Carbon", "Gold"], correct: 1 },
    { q: "What gas makes up 78% of air?", options: ["Oxygen", "Carbon", "Helium", "Nitrogen"], correct: 3 },
    { q: "What is Silver's symbol?", options: ["Si", "Sv", "Ag", "Sr"], correct: 2 },
    { q: "What element is used in wires?", options: ["Gold", "Copper", "Silver", "Iron"], correct: 1 }
  ],
  intermediate: [
    { q: "What element's symbol is Na?", options: ["Nitrogen", "Sodium", "Neon", "Nickel"], correct: 1 },
    { q: "Which element keeps swimming pools clean?", options: ["Sodium", "Sulfur", "Chlorine", "Zinc"], correct: 2 },
    { q: "What smells like rotten eggs?", options: ["Chlorine", "Phosphorus", "Zinc", "Sulfur"], correct: 3 },
    { q: "What element is found in bananas?", options: ["Aluminum", "Potassium", "Silicon", "Tin"], correct: 1 },
    { q: "What is Silicon used in?", options: ["Balloons", "Computer chips", "Jewelry", "Cooking"], correct: 1 },
    { q: "What does Pb stand for?", options: ["Phosphorus", "Platinum", "Lead", "Palladium"], correct: 2 },
    { q: "What element glows in the dark?", options: ["Tin", "Zinc", "Lead", "Phosphorus"], correct: 3 },
    { q: "What metal is the Statue of Liberty made of?", options: ["Gold", "Iron", "Copper", "Aluminum"], correct: 2 },
    { q: "What element protects metals from rusting?", options: ["Zinc", "Tin", "Lead", "Sulfur"], correct: 0 },
    { q: "Where is Silicon Valley named after?", options: ["The Silicon element", "A person named Silicon", "A river", "A mountain"], correct: 0 }
  ],
  advanced: [
    { q: "Which metal has the highest melting point?", options: ["Platinum", "Titanium", "Tungsten", "Uranium"], correct: 2 },
    { q: "What is Tungsten's symbol?", options: ["Tu", "Tg", "W", "Tn"], correct: 2 },
    { q: "What makes rubies red AND emeralds green?", options: ["Cobalt", "Chromium", "Nickel", "Manganese"], correct: 1 },
    { q: "What element is used in nuclear power?", options: ["Neon", "Argon", "Platinum", "Uranium"], correct: 3 },
    { q: "Which noble gas makes signs glow red?", options: ["Helium", "Argon", "Neon", "Krypton"], correct: 2 },
    { q: "What does 'argos' (Argon) mean in Greek?", options: ["Bright", "Lazy", "Heavy", "Hot"], correct: 1 },
    { q: "What element is named after the Titans?", options: ["Titanium", "Plutonium", "Thorium", "Uranium"], correct: 0 },
    { q: "What is Cobalt known for making?", options: ["Red paint", "Blue paint", "Green paint", "Yellow paint"], correct: 1 },
    { q: "A nickel coin is mostly made of what?", options: ["Nickel", "Zinc", "Copper", "Iron"], correct: 2 },
    { q: "Which element makes up about 1% of air?", options: ["Neon", "Argon", "Helium", "Krypton"], correct: 1 }
  ]
};

const STATE_SORTER_ITEMS = [
  { name: "Ice cube", emoji: "🧊", state: "solid" },
  { name: "Water", emoji: "💧", state: "liquid" },
  { name: "Steam", emoji: "♨️", state: "gas" },
  { name: "Rock", emoji: "🪨", state: "solid" },
  { name: "Milk", emoji: "🥛", state: "liquid" },
  { name: "Air", emoji: "💨", state: "gas" },
  { name: "Wood", emoji: "🪵", state: "solid" },
  { name: "Juice", emoji: "🧃", state: "liquid" },
  { name: "Helium", emoji: "🎈", state: "gas" },
  { name: "Diamond", emoji: "💎", state: "solid" },
  { name: "Honey", emoji: "🍯", state: "liquid" },
  { name: "Car exhaust", emoji: "💨", state: "gas" },
  { name: "Gold bar", emoji: "🥇", state: "solid" },
  { name: "Oil", emoji: "🫒", state: "liquid" },
  { name: "Oxygen", emoji: "🫁", state: "gas" },
  { name: "Pencil", emoji: "✏️", state: "solid" },
  { name: "Lava", emoji: "🌋", state: "liquid" },
  { name: "Cloud (water vapor)", emoji: "☁️", state: "gas" },
  { name: "Salt crystal", emoji: "🧂", state: "solid" },
  { name: "Maple syrup", emoji: "🥞", state: "liquid" },
  { name: "Perfume spray", emoji: "🌸", state: "gas" },
  { name: "Chalk", emoji: "📝", state: "solid" },
  { name: "Paint", emoji: "🎨", state: "liquid" },
  { name: "Natural gas", emoji: "🔥", state: "gas" }
];

// ======== SCIENCE BADGES ========
const SCIENCE_BADGES = [
  { id: "sci-first-element", name: "Element Learner", description: "Learn your first element", icon: "⚛️", requirement: { type: "elements_learned", count: 1 } },
  { id: "sci-10-elements", name: "Element Explorer", description: "Learn 10 elements", icon: "🔬", requirement: { type: "elements_learned", count: 10 } },
  { id: "sci-all-elements", name: "Element Master", description: "Learn all 30 elements", icon: "🧪", requirement: { type: "elements_learned", count: 30 } },
  { id: "sci-first-compound", name: "First Compound", description: "Discover your first compound", icon: "⚗️", requirement: { type: "compounds_discovered", count: 1 } },
  { id: "sci-all-compounds", name: "Chemistry Wizard", description: "Discover all 12 compounds", icon: "🧙", requirement: { type: "compounds_discovered", count: 12 } },
  { id: "sci-quiz-perfect", name: "Science Star", description: "Get a perfect score on a science quiz", icon: "🌟", requirement: { type: "science_perfect_quiz", count: 1 } },
  { id: "sci-mix-master", name: "Mix Master", description: "Discover 5 mix lab recipes", icon: "🧫", requirement: { type: "recipes_discovered", count: 5 } },
  { id: "sci-state-sorter", name: "State Sorter Pro", description: "Score 100% on State Sorter", icon: "🏅", requirement: { type: "state_sorter_perfect", count: 1 } }
];
